name: python_ci

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv sync -d
        cp contrib/env-sample .env

    - name: Lint with flake8
      run: pipenv run flake8 .

    - name: Test with pytest
      run: |
        pipenv run pytest . --cov=app

    - name: Upload coverage to Codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: pipenv run codecov
